'use client';
import {useMemo,useState} from 'react';
type Pick={winner:string;games:number}; type Team={code:string;name:string};
const demo:{NHL:Team[];NBA:Team[]}={
 NHL:['WPG','STL','DAL','COL','VGK','MIN','LA','EDM','TOR','OTT','TB','FLA','WSH','MTL','CAR','NJ'].map(code=>({code,name:code})),
 NBA:['OKC','MEM','DEN','LAC','LAL','MIN','GSW','HOU','CLE','MIA','BOS','ORL','NYK','DET','IND','MIL'].map(code=>({code,name:code}))
};
const roundNames=['','Round 1','Round 2','Conference Finals','Championship'];
export default function Brackets(){
 const [sport,setSport]=useState<'NHL'|'NBA'>('NHL'),[picks,setPicks]=useState<Record<string,Pick>>({}),[notice,setNotice]=useState('');const teams=demo[sport];
 const rounds=useMemo(()=>{const r1=Array.from({length:8},(_,i)=>({id:`${sport}-r1-${i+1}`,a:teams[i*2].code,b:teams[i*2+1].code,round:1}));const winner=(id:string)=>picks[id]?.winner||'TBD';const r2=Array.from({length:4},(_,i)=>({id:`${sport}-r2-${i+1}`,a:winner(r1[i*2].id),b:winner(r1[i*2+1].id),round:2}));const r3=Array.from({length:2},(_,i)=>({id:`${sport}-r3-${i+1}`,a:winner(r2[i*2].id),b:winner(r2[i*2+1].id),round:3}));const r4=[{id:`${sport}-r4-1`,a:winner(r3[0].id),b:winner(r3[1].id),round:4}];return [r1,r2,r3,r4]},[sport,teams,picks]);
 function select(id:string,winner:string){if(winner==='TBD')return;setPicks(p=>({...p,[id]:{winner,games:p[id]?.games||6}}))}
 async function submit(){const all=rounds.flat();if(all.some(m=>!picks[m.id]?.winner)){setNotice('Complete all 15 series before submitting.');return}const r=await fetch('/api/brackets/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sport,picks})});const j=await r.json();setNotice(r.ok?`${sport} bracket saved.`:(j.error||'Could not save bracket.'))}
 return <main className="bracketPage"><header className="bracketHeader"><a href="/">← Degens</a><div><b>DEGENS</b><span>PLAYOFF BRACKETS</span></div></header><section className="bracketShell"><div className="bracketHero"><span>FULL FOUR-ROUND BRACKET</span><h1>{sport} Playoff Challenge</h1><p>Pick every series winner and length. Your predicted winners automatically advance into the next round.</p></div><div className="sportSwitch"><button className={sport==='NHL'?'on':''} onClick={()=>{setSport('NHL');setPicks({});setNotice('')}}>🏒 NHL</button><button className={sport==='NBA'?'on':''} onClick={()=>{setSport('NBA');setPicks({});setNotice('')}}>🏀 NBA</button></div><div className="bracketRounds">{rounds.map((round,ri)=><section key={ri}><h2>{roundNames[ri+1]}</h2>{round.map(m=><article className="seriesCard" key={m.id}><button disabled={m.a==='TBD'} className={picks[m.id]?.winner===m.a?'winner':''} onClick={()=>select(m.id,m.a)}><b>{m.a}</b></button><button disabled={m.b==='TBD'} className={picks[m.id]?.winner===m.b?'winner':''} onClick={()=>select(m.id,m.b)}><b>{m.b}</b></button><div className="games"><span>Games</span>{[4,5,6,7].map(n=><button disabled={!picks[m.id]?.winner} className={picks[m.id]?.games===n?'selected':''} key={n} onClick={()=>setPicks(p=>({...p,[m.id]:{winner:p[m.id]?.winner||m.a,games:n}}))}>{n}</button>)}</div></article>)}</section>)}</div>{notice&&<div className="bracketNotice">{notice}</div>}<button className="bracketSubmit" onClick={submit}>Submit Complete {sport} Bracket</button></section></main>
}
