'use client';
import {useEffect,useState,type FormEvent} from 'react';
type Prize={id:string;pool_id:string;title:string;value_cents:number|null;scheduled_draw_at:string|null;week:number|null;eligible_count:number;my_eligible_entries:string[];prize_draws:any[]};
type Pool={id:string;name:string};
const money=(c:number|null)=>c==null?'Value TBA':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100);
export default function Prizes(){
 const [prizes,setPrizes]=useState<Prize[]>([]),[pools,setPools]=useState<Pool[]>([]),[manageable,setManageable]=useState<string[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const [poolId,setPoolId]=useState(''),[name,setName]=useState(''),[week,setWeek]=useState(1),[value,setValue]=useState(''),[drawAt,setDrawAt]=useState(''),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch('/api/prizes');const j=await r.json();if(!r.ok){setMessage(j.error||'Could not load prizes');return}setPrizes(j.prizes||[]);setPools(j.pools||[]);setManageable(j.canManagePoolIds||[]);if(!poolId)setPoolId((j.canManagePoolIds||[])[0]||'')}
 useEffect(()=>{load().finally(()=>setLoading(false))},[]);
 async function create(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const r=await fetch('/api/prizes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({poolId,name,week,valueDollars:value,drawAt:drawAt?new Date(drawAt).toISOString():null,activeOnly:true,onePrizePerEntry:true})});const j=await r.json();if(r.ok){setName('');setValue('');setDrawAt('');setMessage('Prize added to the weekly draw schedule.');await load()}else setMessage(j.error||'Could not add prize');setSaving(false)}
 const upcoming=prizes.filter(p=>!p.prize_draws?.some(d=>d.drawn_at)),past=prizes.filter(p=>p.prize_draws?.some(d=>d.drawn_at));
 return <main className="prizePage"><header className="prizeTop"><a href="/">← Degens</a><div><b>DEGENS</b><span>PRIZE CENTRE</span></div><a href="/live">Spin Wheel</a></header><section className="prizeShell"><div className="prizeHero"><span>WEEKS 1–18 · VERIFIED DRAWS</span><h1>Prizes & Draws</h1><p>Paid, active entries are calculated directly from each league. Every draw saves its eligible list, winner, timestamp and verification record.</p></div>
 {!loading&&manageable.length>0&&<form className="wideCard leagueForm" onSubmit={create}><h2>Add Weekly Prize</h2><label className="fieldLabel">League<select className="textInput" value={poolId} onChange={e=>setPoolId(e.target.value)}>{pools.filter(p=>manageable.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="fieldLabel">Week<select className="textInput" value={week} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=><option key={i+1} value={i+1}>Week {i+1}</option>)}</select></label><label className="fieldLabel">Prize name<input className="textInput" value={name} onChange={e=>setName(e.target.value)} placeholder="Signed jersey" required/></label><label className="fieldLabel">Value (CAD)<input className="textInput" type="number" min="0" step=".01" value={value} onChange={e=>setValue(e.target.value)} placeholder="500"/></label><label className="fieldLabel">Draw date and time<input className="textInput" type="datetime-local" value={drawAt} onChange={e=>setDrawAt(e.target.value)}/></label><button className="primary" disabled={saving}>{saving?'Adding…':'Add Prize'}</button></form>}
 {message&&<div className="notice">{message}</div>}{loading?<div className="notice">Loading prizes…</div>:<><div className="prizeSummary"><div><b>{upcoming.length}</b><span>Upcoming</span></div><div><b>{past.length}</b><span>Completed</span></div><div><b>{prizes.reduce((n,p)=>n+p.eligible_count,0)}</b><span>Eligible entries</span></div></div><h2>Upcoming Draws</h2><div className="prizeGrid">{upcoming.map(p=><article className="prizeCard" key={p.id}><div className="prizeSport">🏆 {p.week?`WEEK ${p.week}`:'SPECIAL DRAW'}</div><h3>{p.title}</h3><b className="prizeValue">{money(p.value_cents)}</b><div className="prizeMeta"><span>{p.scheduled_draw_at?new Date(p.scheduled_draw_at).toLocaleString():'Date TBA'}</span><span>{p.eligible_count} eligible paid entries</span></div><div className={p.my_eligible_entries.length?'elig yes':'elig'}>{p.my_eligible_entries.length?`✓ Eligible: ${p.my_eligible_entries.join(', ')}`:'No eligible entry on this account'}</div></article>)}</div>{upcoming.length===0&&<div className="notice">No upcoming prizes scheduled.</div>}<h2>Past Winners</h2>{past.length===0?<div className="notice">No completed draws yet.</div>:past.map(p=>{const d=p.prize_draws.find(x=>x.drawn_at);const winner=d?.eligible_snapshot?.find((e:any)=>e.id===d.winner_entry_id);return <div className="pastPrize" key={p.id}><div><strong>{p.week?`Week ${p.week} · `:''}{p.title}</strong><span>{winner?.name||'Winner recorded'} · {money(p.value_cents)}</span></div><div><small>VERIFIED DRAW</small><a href={`/api/draws/verify?id=${d.id}`} target="_blank">Verify</a></div></div>})}</>}</section></main>
}
