'use client';
import {useEffect,useState} from 'react';
type Prize={id:string;title:string;description?:string;value_cents:number|null;scheduled_draw_at:string|null;eligible_count:number;my_eligible_entries:string[];prize_draws:any[]};
const money=(c:number|null)=>c==null?'Value TBA':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100);
export default function Prizes(){
 const [prizes,setPrizes]=useState<Prize[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/prizes').then(r=>r.json()).then(j=>setPrizes(j.prizes||[])).finally(()=>setLoading(false))},[]);
 const upcoming=prizes.filter(p=>!p.prize_draws?.some(d=>d.drawn_at)),past=prizes.filter(p=>p.prize_draws?.some(d=>d.drawn_at));
 return <main className="prizePage"><header className="prizeTop"><a href="/">← Degens</a><div><b>DEGENS</b><span>PRIZE CENTRE</span></div><a href="/live">🔴 Live</a></header><section className="prizeShell"><div className="prizeHero"><span>VERIFIED ELIGIBILITY</span><h1>Prizes & Draws</h1><p>Eligibility is calculated from actual paid entries. Completed draws retain an auditable verification record.</p></div>{loading?<div className="notice">Loading prizes…</div>:<><div className="prizeSummary"><div><b>{upcoming.length}</b><span>Upcoming</span></div><div><b>{past.length}</b><span>Completed</span></div><div><b>{prizes.reduce((n,p)=>n+p.eligible_count,0)}</b><span>Eligibility records</span></div></div><h2>Upcoming Draws</h2><div className="prizeGrid">{upcoming.map(p=><article className="prizeCard" key={p.id}><div className="prizeSport">🏆 DRAW</div><h3>{p.title}</h3><b className="prizeValue">{money(p.value_cents)}</b><div className="prizeMeta"><span>{p.scheduled_draw_at?new Date(p.scheduled_draw_at).toLocaleString():'Date TBA'}</span><span>{p.eligible_count} eligible paid entries</span></div><div className={p.my_eligible_entries.length?'elig yes':'elig'}>{p.my_eligible_entries.length?`✓ Eligible: ${p.my_eligible_entries.join(', ')}`:'No eligible entry on this account'}</div></article>)}</div><h2>Past Winners</h2>{past.length===0?<div className="notice">No completed connected draws yet.</div>:past.map(p=>{const d=p.prize_draws.find(x=>x.drawn_at);return <div className="pastPrize" key={p.id}><div><strong>{p.title}</strong><span>{money(p.value_cents)}</span></div><div><small>VERIFIED DRAW</small><a href={`/api/draws/verify?id=${d.id}`} target="_blank">{d.id.slice(0,8)}…</a></div></div>})}</>}</section></main>
}
