'use client';
import {useEffect,useMemo,useState} from 'react';

type Entry={id:string;entry_name:string;pool_id:string}; type Round={id:string;pool_id:string;name:string;sequence:number}; type Player={id:string;full_name:string;team_code:string;position:string;used:boolean;kickoff:string|null};
const slots=[['QB','QB'],['RB1','RB'],['RB2','RB'],['WR1','WR'],['WR2','WR'],['TE','TE']] as const;
export default function Fantasy(){
 const [entries,setEntries]=useState<Entry[]>([]),[rounds,setRounds]=useState<Round[]>([]),[entryId,setEntryId]=useState(''),[roundId,setRoundId]=useState(''),[players,setPlayers]=useState<Player[]>([]),[lineup,setLineup]=useState<Record<string,Player>>({}),[slot,setSlot]=useState('QB'),[notice,setNotice]=useState('');
 useEffect(()=>{fetch('/api/bootstrap').then(r=>r.json()).then(b=>{const pools=new Set((b.pools||[]).filter((p:any)=>p.sport==='NFL'&&p.contest_type==='PLAYOFF_FANTASY').map((p:any)=>p.id));const es=(b.entries||[]).filter((e:any)=>pools.has(e.pool_id));setEntries(es);setRounds((b.rounds||[]).filter((r:any)=>pools.has(r.pool_id)));if(es[0])setEntryId(es[0].id)}).catch(()=>{})},[]);
 useEffect(()=>{if(!entryId)return;const e=entries.find(x=>x.id===entryId);const rs=rounds.filter(r=>r.pool_id===e?.pool_id).sort((a,b)=>a.sequence-b.sequence);if(rs[0]&&!rs.some(r=>r.id===roundId))setRoundId(rs[0].id)},[entryId,entries,rounds,roundId]);
 useEffect(()=>{if(!entryId||!roundId)return;fetch(`/api/fantasy/players?entryId=${encodeURIComponent(entryId)}&roundId=${encodeURIComponent(roundId)}`).then(r=>r.json()).then(j=>{setPlayers(j.players||[]);if(j.error)setNotice(j.error)}).catch(()=>{})},[entryId,roundId]);
 const pos=slots.find(s=>s[0]===slot)?.[1]||'QB', available=useMemo(()=>players.filter(p=>p.position===pos),[players,pos]);
 async function choose(p:Player){if(p.used)return;const r=await fetch('/api/picks/fantasy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entryId,roundId,slot,athleteId:p.id})});const j=await r.json();if(!r.ok){setNotice(j.error||'Could not save pick');return}setLineup(x=>({...x,[slot]:p}));setNotice(`${p.full_name} saved at ${slot}.`)}
 return <main className="featurePage"><header className="featureTop"><a href="/">← Degens</a><b>NFL PLAYOFF FANTASY</b><a href="/">Home</a></header><section className="featureShell"><div className="featureHero"><span>QB · RB · RB · WR · WR · TE</span><h1>Build each playoff-round lineup</h1><p>Every player can be used only once by that entry. Fantasy points accumulate through the Super Bowl.</p></div><div className="twoSelects"><select value={entryId} onChange={e=>setEntryId(e.target.value)}>{entries.map(e=><option key={e.id} value={e.id}>{e.entry_name}</option>)}</select><select value={roundId} onChange={e=>setRoundId(e.target.value)}>{rounds.filter(r=>r.pool_id===entries.find(e=>e.id===entryId)?.pool_id).sort((a,b)=>a.sequence-b.sequence).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="lineupSlots">{slots.map(([s])=><button key={s} className={slot===s?'activeSlot':''} onClick={()=>setSlot(s)}><small>{s}</small><b>{lineup[s]?.full_name||'Select player'}</b><span>{lineup[s]?.team_code||''}</span></button>)}</div><h2>Available {pos}s</h2><div className="playerList">{available.map(p=><button key={p.id} disabled={p.used} onClick={()=>choose(p)}><div><b>{p.full_name}</b><span>{p.team_code}{p.kickoff?` · ${new Date(p.kickoff).toLocaleString()}`:''}</span></div><small>{p.used?'USED':'SELECT'}</small></button>)}</div>{notice&&<div className="notice">{notice}</div>}</section></main>
}
