'use client';
import {useEffect,useMemo,useState} from 'react';
import LiveBroadcast from '@/components/LiveBroadcast';
import {createClient} from '@/lib/supabase/client';
type Entry={id:string;name:string};type Prize={id:string;title:string;week:number|null;eligible_count:number;eligible_entries?:Entry[];prize_draws?:any[]};
const colors=['#c8ff35','#6ee7ff','#a78bfa','#fb7185','#fbbf24','#34d399','#60a5fa','#f472b6'];
export default function LiveDraw(){
 const [prizes,setPrizes]=useState<Prize[]>([]),[prizeId,setPrizeId]=useState(''),[winner,setWinner]=useState<string|null>(null),[drawing,setDrawing]=useState(false),[audit,setAudit]=useState<any>(null),[isHost,setIsHost]=useState(false),[rotation,setRotation]=useState(0),[message,setMessage]=useState('');
 const [roleReady,setRoleReady]=useState(false),[viewerMode,setViewerMode]=useState(false),[copied,setCopied]=useState(false);
 async function api(path:string,init:RequestInit={}){const {data}=await createClient().auth.getSession();const headers=new Headers(init.headers);if(data.session?.access_token)headers.set('authorization',`Bearer ${data.session.access_token}`);return fetch(path,{...init,headers})}
 async function load(forceViewer=viewerMode){const r=await api('/api/prizes');const j=await r.json();if(r.status===401&&j.error==='UNAUTHENTICATED'){window.location.replace('/auth/login?next=/live&reason=session');return}if(!r.ok){setMessage(j.error||'Could not load draws');return}const upcoming=(j.prizes||[]).filter((p:any)=>!p.prize_draws?.some((d:any)=>d.drawn_at));setPrizes(upcoming);setPrizeId(x=>upcoming.some((p:any)=>p.id===x)?x:(upcoming[0]?.id||''));setIsHost((j.canManagePoolIds||[]).length>0&&!forceViewer)}
 useEffect(()=>{const viewer=new URLSearchParams(window.location.search).get('viewer')==='1';setViewerMode(viewer);load(viewer).finally(()=>setRoleReady(true))},[]);
 async function copyViewerLink(){const link=`${window.location.origin}/live?viewer=1`;try{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{window.prompt('Copy this viewer link:',link)}}
 const selected=prizes.find(p=>p.id===prizeId),eligible=selected?.eligible_entries||[],count=eligible.length;
 const gradient=useMemo(()=>count?eligible.map((_,i)=>`${colors[i%colors.length]} ${i*100/count}% ${(i+1)*100/count}%`).join(','):'#222 0 100%',[eligible,count]);
 async function draw(){if(!selected||!count||drawing)return;setDrawing(true);setWinner(null);setAudit(null);setMessage('Selecting and recording the winner…');const r=await api('/api/admin/draw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prizeId:selected.id})});const j=await r.json();if(!r.ok){setDrawing(false);setMessage(j.error||'Draw failed');return}const slice=360/j.eligibleCount,target=360-(j.winnerIndex*slice+slice/2);setRotation(x=>x+1800+target-(x%360));setMessage('Wheel spinning…');setTimeout(()=>{setDrawing(false);setWinner(j.winner.name);setAudit(j);setMessage('Winner recorded and draw locked.');load()},4200)}
 return <main className="drawPage"><header className="drawTop"><a href="/">← Degens</a><div><b>🔴 LIVE DRAW ROOM</b><span>{viewerMode?'Viewer mode':'Weekly verified prize wheel'}</span></div><a href="/prizes">Prize Centre</a></header>{isHost&&<section className="broadcastSetup"><div><strong>Commissioner broadcast</strong><span>Turn on Camera and Microphone, then choose Share screen and select this browser tab. Keep both camera and screen share on while spinning.</span></div><button type="button" onClick={copyViewerLink}>{copied?'Viewer Link Copied ✓':'Copy Viewer Link'}</button><a href="/live?viewer=1" target="_blank">Preview Viewer Mode</a></section>}<section className="drawLayout"><div className="broadcast">{roleReady?<LiveBroadcast asHost={isHost}/>:<div className="videoPlaceholder"><strong>Preparing live room…</strong></div>}<div className="liveMeta"><b>Degens Prize Night</b><span>{isHost?'Camera · microphone · share this tab':'Watch-only · camera, audio and wheel broadcast'}</span></div></div>{isHost&&<aside className="drawControl"><span className="kicker">CURRENT DRAW</span>{prizes.length?<select value={prizeId} onChange={e=>{setPrizeId(e.target.value);setWinner(null);setAudit(null)}}>{prizes.map(p=><option key={p.id} value={p.id}>{p.week?`Week ${p.week} · `:''}{p.title}</option>)}</select>:<div className="notice">No upcoming prizes. Add one in Prize Centre.</div>}<div className="eligibleTitle"><b>Eligible paid entries</b><span>{count}</span></div><div className="chips">{eligible.slice(0,100).map(e=><span key={e.id}>{e.name}</span>)}</div><button className="drawButton" disabled={drawing||!selected||!count} onClick={draw}>{drawing?'SPINNING…':'SPIN & DRAW WINNER'}</button>{message&&<div className="notice">{message}</div>}</aside>}<section className="wheelStage"><div className="wheelPointer">▼</div><div className="wheel" style={{background:`conic-gradient(${gradient})`,transform:`rotate(${rotation}deg)`,transition:drawing?'transform 4s cubic-bezier(.08,.72,.08,1)':'none'}}>{count>0&&eligible.slice(0,Math.min(count,24)).map((e,i)=><span key={e.id} style={{transform:`rotate(${i*360/Math.min(count,24)}deg) translateY(-112px)`}}>{e.name.slice(0,12)}</span>)}</div>{winner&&<div className="winnerCard"><span>🏆 WINNER</span><h1>{winner}</h1>{audit&&<><small>Draw ID: {audit.drawId}</small><small>{audit.eligibleCount} eligible entries</small><a href={`/api/draws/verify?id=${audit.drawId}`} target="_blank">Verify draw</a></>}</div>}</section></section></main>
}
