'use client';
import {useEffect,useMemo,useState} from 'react';
import LiveBroadcast from '@/components/LiveBroadcast';

type Prize={id:string;title:string;value_cents:number|null;eligible_count:number;prize_draws?:any[]};
export default function LiveDraw(){
 const [eligible,setEligible]=useState([{id:'demo-1',name:'Rouge91'},{id:'demo-2',name:'HMundi'},{id:'demo-3',name:'SunnyS'}]);
 const [prizes,setPrizes]=useState<Prize[]>([]),[prizeId,setPrizeId]=useState(''),[winner,setWinner]=useState<string|null>(null),[drawing,setDrawing]=useState(false),[audit,setAudit]=useState<any>(null),[connected,setConnected]=useState(false),[isHost,setIsHost]=useState(false);
 useEffect(()=>{fetch('/api/bootstrap').then(r=>r.ok?r.json():null).then(b=>setIsHost(!!b?.profile?.is_commissioner)).catch(()=>{});fetch('/api/prizes').then(r=>r.json()).then(j=>{if(j.prizes?.length){setPrizes(j.prizes);setPrizeId(j.prizes[0].id);setConnected(true)}}).catch(()=>{})},[]);
 const selected=prizes.find(p=>p.id===prizeId),rotation=useMemo(()=>Math.max(720,(selected?.eligible_count||eligible.length)*30),[selected,eligible.length]);
 async function draw(){setDrawing(true);setWinner(null);setAudit(null);const body=connected?{prizeId}:{eligibleEntries:eligible,prizeTitle:'Demo Prize'};const r=await fetch('/api/admin/draw',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setTimeout(()=>{setDrawing(false);if(r.ok){setWinner(j.winner.name);setAudit(j)}else alert(j.error||'Draw failed')},1700)}
 return <main className="drawPage"><header className="drawTop"><a href="/">← Degens</a><div><b>🔴 LIVE DRAW ROOM</b><span>Commissioner broadcast console</span></div><a href="/prizes">Prize Centre</a></header><section className="drawLayout"><div className="broadcast"><LiveBroadcast asHost={isHost}/><div className="liveMeta"><b>Degens Prize Night</b><span>Camera · microphone · screen share · chat</span></div></div>{isHost&&<aside className="drawControl"><span className="kicker">CURRENT DRAW</span>{connected?<select value={prizeId} onChange={e=>setPrizeId(e.target.value)}>{prizes.filter((p:any)=>!p.prize_draws?.some((d:any)=>d.drawn_at)).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select>:<><b>Demo Prize</b><div className="chips">{eligible.map(e=><button key={e.id} onClick={()=>setEligible(x=>x.filter(y=>y.id!==e.id))}>{e.name} ×</button>)}</div></>}<div className="eligibleTitle"><b>Eligible paid entries</b><span>{connected?(selected?.eligible_count||0):eligible.length}</span></div><button className="drawButton" disabled={drawing} onClick={draw}>{drawing?'DRAWING…':'SPIN & DRAW WINNER'}</button></aside>}<section className="wheelStage"><div className={`wheel ${drawing?'spinning':''}`} style={{'--spin':`${rotation}deg`} as React.CSSProperties}/>{winner&&<div className="winnerCard"><span>🏆 WINNER</span><h1>{winner}</h1>{audit&&<><small>Draw ID: {audit.drawId}</small><small>Verification: {audit.verificationHash.slice(0,32)}…</small><a href={`/api/draws/verify?id=${audit.drawId}`} target="_blank">Verify draw</a></>}</div>}</section></section></main>
}
