'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import PickReceipts from '@/components/PickReceipts';

type LeagueData={pool:any;members:any[];entries:any[];picks:any[];games:any[];standings:any[];latestScoringRun:any|null;audit:any[];history:any[]};

export default function LeagueManagementPage(){
  const {poolId}=useParams<{poolId:string}>();
  const [data,setData]=useState<LeagueData|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);const [inviteCode,setInviteCode]=useState('');
  const [scoringWeek,setScoringWeek]=useState('1');const [correction,setCorrection]=useState({gameId:'',awayScore:'',homeScore:''});const [scoringNotice,setScoringNotice]=useState('');const [scoringBusy,setScoringBusy]=useState(false);const [entryDrafts,setEntryDrafts]=useState<Record<string,any>>({});const [renewing,setRenewing]=useState(false);
  const [bracketTeams,setBracketTeams]=useState('');
  const [deleteConfirmation,setDeleteConfirmation]=useState('');
  const [form,setForm]=useState({name:'',maxEntries:'1',maxParticipants:'1000',deadlineMode:'GAME_KICKOFF',strictMissedPicks:true,visibility:'INVITE_ONLY',isActive:true});
  async function load(){const response=await fetch(`/api/leagues/${poolId}`);const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load league.');setData(result);setEntryDrafts(Object.fromEntries((result.entries||[]).map((entry:any)=>[entry.id,{entryName:entry.entry_name,paymentStatus:entry.payment_status,entryStatus:entry.entry_status}])));const p=result.pool;setForm({name:p.name,maxEntries:String(p.max_entries_per_user||1),maxParticipants:String(p.max_participants||1000),deadlineMode:p.scoring_settings?.deadline_mode||'GAME_KICKOFF',strictMissedPicks:p.scoring_settings?.missed_pick_elimination!==false,visibility:p.visibility||'INVITE_ONLY',isActive:p.is_active!==false});}
  useEffect(()=>{load().catch(reason=>setError(reason.message));},[poolId]);
  const update=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setNotice('');const response=await fetch(`/api/leagues/${poolId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const result=await response.json();setSaving(false);if(!response.ok){setNotice(result.error||'Could not save settings.');return;}setData(current=>current?{...current,pool:result.pool}:current);setNotice('League settings saved.');}
  async function action(action:string,payload:Record<string,any>={}){const scoringAction=action==='run_scoring'||action==='correct_game';setNotice('');if(scoringAction){setScoringNotice('');setScoringBusy(true);}try{const response=await fetch(`/api/leagues/${poolId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})});const result=await response.json();if(!response.ok){const message=result.error||'Action failed.';if(scoringAction)setScoringNotice(message);else setNotice(message);return;}if(result.inviteCode)setInviteCode(result.inviteCode);else await load();const message=action==='regenerate_invite'?'New invitation code created.':action==='confirm_bracket_matchups'?'Playoff matchups confirmed. Players can now submit picks.':action==='run_scoring'?`Week ${payload.week} scores synced and standings updated.`:action==='correct_game'?'Final score corrected and the week was regraded.':action==='update_member'?'Member status updated.':action==='update_entry'?'Entry updated.':'Entry deactivated.';if(scoringAction)setScoringNotice(message);else setNotice(message);}catch{const message='Could not complete the commissioner action. Please try again.';if(scoringAction)setScoringNotice(message);else setNotice(message);}finally{if(scoringAction)setScoringBusy(false);}}
  function confirmBracket(){const teams=bracketTeams.split(/\r?\n|,/).map(team=>team.trim()).filter(Boolean);action('confirm_bracket_matchups',{teams});}
  async function renewSeason(){if(!data||renewing)return;const nextSeason=Number(data.pool.season)+1;if(!window.confirm(`Create the ${nextSeason} season from this league's settings? This starts a fresh league with a new invite code.`))return;setRenewing(true);setNotice('');try{const response=await fetch(`/api/leagues/${poolId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'renew_season',nextSeason})});const result=await response.json();if(!response.ok){setNotice(result.error||'Could not renew season.');return;}const renewed=result.league?.pool||result.league;setNotice(`Season ${nextSeason} created. A fresh invite code was generated.`);if(renewed?.id)window.setTimeout(()=>window.location.href=`/leagues/${renewed.id}`,500);}catch{setNotice('Could not renew season. Please try again.');}finally{setRenewing(false);}}
  async function deleteLeague(){if(!data||deleteConfirmation.trim()!=='delete')return;setSaving(true);setNotice('Deleting league…');try{const response=await fetch(`/api/leagues/${poolId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete_league'})});const result=await response.json();if(!response.ok){setNotice(result.error||'Could not delete league.');return;}window.location.href='/';}catch{setNotice('Could not delete league. Please try again.');}finally{setSaving(false);}}
  if(error)return <main className="shell"><div className="warning">{error}</div><a className="authLink" href="/">Back to dashboard</a></main>;
  if(!data)return <main className="shell"><div className="wideCard"><span>Loading league…</span></div></main>;
  const entryNames=new Map(data.entries.map(entry=>[entry.id,entry.entry_name]));
  const weeks=[...new Set((data.games||[]).map(game=>Number(game.week)))].sort((a,b)=>a-b);
  const selectedGame=(data.games||[]).find(game=>game.id===correction.gameId);
  const latestRun=data.latestScoringRun;
  const latestRunTime=latestRun?.completed_at?new Date(latestRun.completed_at).toLocaleString():null;
  return <main className="leagueAdminPage"><header className="leagueAdminTop"><a href="/">← Dashboard</a><div><span>COMMISSIONER</span><b>{data.pool.name}</b></div><a href={`/prizes?mode=commissioner&pool=${poolId}`}>Prizes</a></header><section className="leagueAdminShell">
    <div className="leagueAdminHero"><div><span>{data.pool.sport} · {data.pool.pool_type.replaceAll('_',' ')}</span><h1>{data.pool.name}</h1><p>{data.members.filter(member=>member.status==='ACTIVE').length} participants · {data.entries.filter(entry=>entry.entry_status==='ACTIVE').length} active entries</p></div><button onClick={()=>action('regenerate_invite')}>Generate New Invite Code</button></div>
    {inviteCode&&<div className="inviteBanner"><span>New invitation code — copy it now</span><strong>{inviteCode}</strong></div>}{notice&&<div className="notice">{notice}</div>}
    <div className="leagueAdminGrid"><section className="adminPanel"><h2>League Settings</h2><label>League name<input value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Entries per member<input type="number" min="1" max="100" value={form.maxEntries} onChange={e=>update('maxEntries',e.target.value)}/></label><label>Maximum participants<input type="number" min="1" max="1000" value={form.maxParticipants} onChange={e=>update('maxParticipants',e.target.value)}/></label><label>Pick deadline<select value={form.deadlineMode} onChange={e=>update('deadlineMode',e.target.value)}><option value="GAME_KICKOFF">Each game’s kickoff</option><option value="SUNDAY_10AM_PT">Sunday at 10:00 AM PT</option></select></label><label>Visibility<select value={form.visibility} onChange={e=>update('visibility',e.target.value)}><option value="INVITE_ONLY">Invite only</option><option value="PUBLIC">Public</option></select></label>{data.pool.pool_type==='SURVIVOR'&&<label className="checkRow"><input type="checkbox" checked={form.strictMissedPicks} onChange={e=>update('strictMissedPicks',e.target.checked)}/> Eliminate missed picks</label>}<label className="checkRow"><input type="checkbox" checked={form.isActive} onChange={e=>update('isActive',e.target.checked)}/> League is open for play</label><button className="adminPrimary" disabled={saving} onClick={save}>{saving?'Saving…':'Save Settings'}</button><button className="secondary" disabled={renewing||saving} onClick={renewSeason}>{renewing?'Creating new season…':'Renew Season'}</button><div className="dangerZone"><h3>Delete league</h3><p className="muted">Permanently removes this league and all of its entries, picks, prizes, invites, and season data. Type <strong>delete</strong> to continue.</p><label>Confirmation<input value={deleteConfirmation} onChange={event=>setDeleteConfirmation(event.target.value)} placeholder="Type delete" autoComplete="off" spellCheck={false}/></label><button className="dangerButton" disabled={saving||renewing||deleteConfirmation.trim()!=='delete'} onClick={deleteLeague}>{saving&&notice==='Deleting league…'?'Deleting…':'Delete League Permanently'}</button></div></section>
      <section className="adminPanel"><h2>League History</h2><p className="muted">Past seasons stay separate so picks, standings, and audit records remain permanent.</p>{data.history.length===0?<p className="muted">This is the first season in this league series.</p>:data.history.map(item=><a className="manageRow historyRow" href={`/leagues/${item.id}`} key={item.id}><div><strong>{item.name}</strong><span>Season {item.season} · {item.is_active?'Open':'Closed'}</span></div><b>{item.id===data.pool.id?'Current':'View'}</b></a>)}</section>
      <section className="adminPanel"><h2>Members & Entries</h2><p className="muted">Update roster status, payment tracking, and entry eligibility. Changes are logged for the league.</p>{data.entries.map(entry=>{const draft=entryDrafts[entry.id]||entry;const member=data.members.find(member=>member.user_id===entry.user_id);return <div className="manageRow entryManageRow" key={entry.id}><div><strong>{entry.entry_name}</strong><span>{entry.profile?.display_name||entry.profile?.username||entry.user_id}</span><small>{member?.role||'PLAYER'} · {member?.status||'ACTIVE'}</small></div><div className="entryControls"><input aria-label="Entry name" value={draft.entryName} onChange={event=>setEntryDrafts(current=>({...current,[entry.id]:{...draft,entryName:event.target.value}}))}/><select aria-label="Payment status" value={draft.paymentStatus} onChange={event=>setEntryDrafts(current=>({...current,[entry.id]:{...draft,paymentStatus:event.target.value}}))}><option>UNPAID</option><option>PAID</option><option>WAIVED</option><option>REFUNDED</option></select><select aria-label="Entry status" value={draft.entryStatus} onChange={event=>setEntryDrafts(current=>({...current,[entry.id]:{...draft,entryStatus:event.target.value}}))}><option>ACTIVE</option><option>INACTIVE</option><option>ELIMINATED</option></select><button onClick={()=>action('update_entry',{entryId:entry.id,...draft})}>Save</button></div>{member&&member.role!=='COMMISSIONER'&&<div className="memberActions"><button onClick={()=>action('update_member',{userId:member.user_id,status:member.status==='ACTIVE'?'SUSPENDED':'ACTIVE'})}>{member.status==='ACTIVE'?'Suspend member':'Restore member'}</button>{member.status!=='LEFT'&&<button className="dangerButton" onClick={()=>{if(window.confirm('Remove this member from the league? Their entries will be deactivated and preserved in the audit history.'))action('remove_member',{userId:member.user_id});}}>Remove member</button>}</div>}</div>})}</section>
      <section className="adminPanel"><h2>Submitted Picks</h2>{data.picks.length===0?<p className="muted">No picks submitted yet.</p>:data.picks.map((pick,index)=><div className="manageRow" key={pick.id||index}><div><strong>{entryNames.get(pick.entry_id)||'Entry'}</strong><span>{pick.team_code||pick.selected_team||pick.athlete_id||pick.winner_team||'Submitted'}{pick.week?` · Week ${pick.week}`:''}</span></div></div>)}</section>
      {data.pool.pool_type==='BRACKET'&&<section className="adminPanel"><h2>Playoff Matchups</h2><p className="muted">Keep this locked until the official {data.pool.sport} playoff field is confirmed. Enter the 16 teams in Round 1 order, one per line.</p>{data.picks.some((pick:any)=>pick.matchup_id)?<div className="notice">Bracket picks have been submitted. Matchups are locked.</div>:<><textarea className="textInput" rows={8} value={bracketTeams} onChange={event=>setBracketTeams(event.target.value)} placeholder={'Team 1\nTeam 2\nTeam 3\n…\nTeam 16'}/><button className="adminPrimary" disabled={bracketTeams.split(/\r?\n|,/).filter(team=>team.trim()).length!==16} onClick={confirmBracket}>Confirm Official Playoff Matchups</button></>}</section>}
      <section className="adminPanel"><PickReceipts poolId={poolId} /></section>
      <section className="adminPanel"><h2>League Standings</h2>{data.standings.map((entry,index)=><div className="manageRow" key={entry.entry_id}><b>#{index+1}</b><div className="grow"><strong>{entry.entry_name}</strong><span>{entry.entry_status} · {entry.wins} wins · {entry.losses} losses · {entry.pending} pending</span></div></div>)}</section>
      <section className="adminPanel"><h2>Commissioner Activity</h2><p className="muted">Recent settings, roster, scoring, prize, and draw actions for this organization.</p>{data.audit.length===0?<p className="muted">No commissioner activity yet.</p>:data.audit.map(item=><div className="manageRow" key={item.id}><div><strong>{item.action.replaceAll('_',' ')}</strong><span>{item.entity_type} · {new Date(item.created_at).toLocaleString()}</span><small>{item.payload?.after?.entry_status||item.payload?.after?.status||item.payload?.name||''}</small></div></div>)}</section>
      {data.pool.sport==='NFL'&&<section className="adminPanel"><h2>Automatic Scoring</h2><div className={latestRun?.status==='FAILED'?'warning':'notice'}><strong>{latestRun?.status==='FAILED'?'Automatic scoring needs attention':'Automatic scoring is active'}</strong><span>{latestRunTime?` Last ${latestRun.status==='SUCCEEDED'?'successful ':''}check: ${latestRunTime} · Week ${latestRun.week}.`:' Scores are checked automatically from the verified NFL feed.'}</span>{latestRun?.error_message&&<small>{latestRun.error_message}</small>}</div><p className="muted">Final scores automatically grade Pick’em, update standings, and eliminate losing or missed Survivor entries. The nightly verification is backed up by live refreshes while members use the app.</p><label>Week<select value={scoringWeek} onChange={event=>setScoringWeek(event.target.value)}>{(weeks.length?weeks:[1]).map(week=><option value={week} key={week}>Week {week}</option>)}</select></label><button className="adminPrimary" disabled={scoringBusy} onClick={()=>action('run_scoring',{week:scoringWeek})}>{scoringBusy?'Checking & grading…':`Run Week ${scoringWeek} Check Now`}</button>{scoringNotice&&<div className="notice">{scoringNotice}</div>}<h3>Commissioner correction</h3><p className="muted">A saved correction is protected from later provider refreshes and regrades the week.</p><label>Game<select value={correction.gameId} onChange={event=>setCorrection({gameId:event.target.value,awayScore:'',homeScore:''})}><option value="">Select a game</option>{(data.games||[]).filter(game=>String(game.week)===scoringWeek).map(game=><option value={game.id} key={game.id}>{game.away_team} at {game.home_team}</option>)}</select></label>{selectedGame&&<div className="settingsPair"><label>{selectedGame.away_team}<input type="number" min="0" value={correction.awayScore} onChange={event=>setCorrection(current=>({...current,awayScore:event.target.value}))}/></label><label>{selectedGame.home_team}<input type="number" min="0" value={correction.homeScore} onChange={event=>setCorrection(current=>({...current,homeScore:event.target.value}))}/></label></div>}<button disabled={scoringBusy||!correction.gameId||correction.awayScore===''||correction.homeScore===''} onClick={()=>action('correct_game',correction)}>Save Final Score & Regrade</button></section>}
    </div>
  </section></main>;
}
