'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';

type LeagueData={pool:any;members:any[];entries:any[];payments:any[];picks:any[];games:any[];standings:any[]};

export default function LeagueManagementPage(){
  const {poolId}=useParams<{poolId:string}>();
  const [data,setData]=useState<LeagueData|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);const [inviteCode,setInviteCode]=useState('');
  const [scoringWeek,setScoringWeek]=useState('1');const [correction,setCorrection]=useState({gameId:'',awayScore:'',homeScore:''});const [scoringNotice,setScoringNotice]=useState('');const [scoringBusy,setScoringBusy]=useState(false);
  const [form,setForm]=useState({name:'',entryFee:'0',maxEntries:'1',maxParticipants:'1000',deadlineMode:'GAME_KICKOFF',strictMissedPicks:true,visibility:'INVITE_ONLY'});
  async function load(){const response=await fetch(`/api/leagues/${poolId}`);const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not load league.');setData(result);const p=result.pool;setForm({name:p.name,entryFee:String((p.entry_fee_cents||0)/100),maxEntries:String(p.max_entries_per_user||1),maxParticipants:String(p.max_participants||1000),deadlineMode:p.scoring_settings?.deadline_mode||'GAME_KICKOFF',strictMissedPicks:p.scoring_settings?.missed_pick_elimination!==false,visibility:p.visibility||'INVITE_ONLY'});}
  useEffect(()=>{load().catch(reason=>setError(reason.message));},[poolId]);
  const update=(key:string,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  async function save(){setSaving(true);setNotice('');const response=await fetch(`/api/leagues/${poolId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const result=await response.json();setSaving(false);if(!response.ok){setNotice(result.error||'Could not save settings.');return;}setData(current=>current?{...current,pool:result.pool}:current);setNotice('League settings saved.');}
  async function action(action:string,payload:Record<string,string>={}){const scoringAction=action==='run_scoring'||action==='correct_game';setNotice('');if(scoringAction){setScoringNotice('');setScoringBusy(true);}try{const response=await fetch(`/api/leagues/${poolId}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})});const result=await response.json();if(!response.ok){const message=result.error||'Action failed.';if(scoringAction)setScoringNotice(message);else setNotice(message);return;}if(result.inviteCode)setInviteCode(result.inviteCode);else await load();const message=action==='regenerate_invite'?'New invitation code created.':action==='verify_payment'?'Payment verified.':action==='run_scoring'?`Week ${payload.week} scores synced and standings updated.`:action==='correct_game'?'Final score corrected and the week was regraded.':'Entry deactivated.';if(scoringAction)setScoringNotice(message);else setNotice(message);}catch{const message='Could not reach the scoring service. Please try again.';if(scoringAction)setScoringNotice(message);else setNotice(message);}finally{if(scoringAction)setScoringBusy(false);}}
  if(error)return <main className="shell"><div className="warning">{error}</div><a className="authLink" href="/">Back to dashboard</a></main>;
  if(!data)return <main className="shell"><div className="wideCard"><span>Loading league…</span></div></main>;
  const entryNames=new Map(data.entries.map(entry=>[entry.id,entry.entry_name]));
  const weeks=[...new Set((data.games||[]).map(game=>Number(game.week)))].sort((a,b)=>a-b);
  const selectedGame=(data.games||[]).find(game=>game.id===correction.gameId);
  return <main className="leagueAdminPage"><header className="leagueAdminTop"><a href="/">← Dashboard</a><div><span>COMMISSIONER</span><b>{data.pool.name}</b></div><a href="/">Make Picks</a></header><section className="leagueAdminShell">
    <div className="leagueAdminHero"><div><span>{data.pool.sport} · {data.pool.pool_type.replaceAll('_',' ')}</span><h1>{data.pool.name}</h1><p>{data.members.filter(member=>member.status==='ACTIVE').length} participants · {data.entries.filter(entry=>entry.entry_status==='ACTIVE').length} active entries</p></div><button onClick={()=>action('regenerate_invite')}>Generate New Invite Code</button></div>
    {inviteCode&&<div className="inviteBanner"><span>New invitation code — copy it now</span><strong>{inviteCode}</strong></div>}{notice&&<div className="notice">{notice}</div>}
    <div className="leagueAdminGrid"><section className="adminPanel"><h2>League Settings</h2><label>League name<input value={form.name} onChange={e=>update('name',e.target.value)}/></label><div className="settingsPair"><label>Entry fee (CAD)<input type="number" min="0" value={form.entryFee} onChange={e=>update('entryFee',e.target.value)}/></label><label>Entries per member<input type="number" min="1" max="100" value={form.maxEntries} onChange={e=>update('maxEntries',e.target.value)}/></label></div><label>Maximum participants<input type="number" min="1" max="1000" value={form.maxParticipants} onChange={e=>update('maxParticipants',e.target.value)}/></label><label>Pick deadline<select value={form.deadlineMode} onChange={e=>update('deadlineMode',e.target.value)}><option value="GAME_KICKOFF">Each game’s kickoff</option><option value="SUNDAY_10AM_PT">Sunday at 10:00 AM PT</option></select></label><label>Visibility<select value={form.visibility} onChange={e=>update('visibility',e.target.value)}><option value="INVITE_ONLY">Invite only</option><option value="PUBLIC">Public</option></select></label>{data.pool.pool_type==='SURVIVOR'&&<label className="checkRow"><input type="checkbox" checked={form.strictMissedPicks} onChange={e=>update('strictMissedPicks',e.target.checked)}/> Eliminate missed picks</label>}<button className="adminPrimary" disabled={saving} onClick={save}>{saving?'Saving…':'Save Settings'}</button></section>
      <section className="adminPanel"><h2>Members & Entries</h2>{data.entries.map(entry=><div className="manageRow" key={entry.id}><div><strong>{entry.entry_name}</strong><span>{entry.payment_status} · {entry.entry_status}</span><small>{entry.user_id}</small></div>{entry.entry_status==='ACTIVE'&&<button onClick={()=>action('deactivate_entry',{entryId:entry.id})}>Deactivate</button>}</div>)}</section>
      <section className="adminPanel"><h2>Payments</h2>{data.payments.length===0?<p className="muted">No payments submitted.</p>:data.payments.map(payment=><div className="manageRow" key={payment.id}><div><strong>{entryNames.get(payment.entry_id)||'Entry'}</strong><span>{new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(payment.amount_cents/100)} · {payment.status}</span></div>{payment.status==='PENDING'&&<button onClick={()=>action('verify_payment',{paymentId:payment.id})}>Verify Paid</button>}</div>)}</section>
      <section className="adminPanel"><h2>Submitted Picks</h2>{data.picks.length===0?<p className="muted">No picks submitted yet.</p>:data.picks.map((pick,index)=><div className="manageRow" key={pick.id||index}><div><strong>{entryNames.get(pick.entry_id)||'Entry'}</strong><span>{pick.team_code||pick.selected_team||pick.athlete_id||pick.winner_team||'Submitted'}{pick.week?` · Week ${pick.week}`:''}</span></div></div>)}</section>
      <section className="adminPanel"><h2>League Standings</h2>{data.standings.map((entry,index)=><div className="manageRow" key={entry.entry_id}><b>#{index+1}</b><div className="grow"><strong>{entry.entry_name}</strong><span>{entry.entry_status} · {entry.wins} wins · {entry.losses} losses · {entry.pending} pending</span></div></div>)}</section>
      {data.pool.sport==='NFL'&&<section className="adminPanel"><h2>Scoring & Results</h2><p className="muted">Sync final NFL scores, grade Pick’em picks, and eliminate losing or missed Survivor entries.</p><label>Week<select value={scoringWeek} onChange={event=>setScoringWeek(event.target.value)}>{(weeks.length?weeks:[1]).map(week=><option value={week} key={week}>Week {week}</option>)}</select></label><button className="adminPrimary" disabled={scoringBusy} onClick={()=>action('run_scoring',{week:scoringWeek})}>{scoringBusy?'Syncing & grading…':`Sync & Grade Week ${scoringWeek}`}</button>{scoringNotice&&<div className="notice">{scoringNotice}</div>}<h3>Correct a final score</h3><label>Game<select value={correction.gameId} onChange={event=>setCorrection({gameId:event.target.value,awayScore:'',homeScore:''})}><option value="">Select a game</option>{(data.games||[]).filter(game=>String(game.week)===scoringWeek).map(game=><option value={game.id} key={game.id}>{game.away_team} at {game.home_team}</option>)}</select></label>{selectedGame&&<div className="settingsPair"><label>{selectedGame.away_team}<input type="number" min="0" value={correction.awayScore} onChange={event=>setCorrection(current=>({...current,awayScore:event.target.value}))}/></label><label>{selectedGame.home_team}<input type="number" min="0" value={correction.homeScore} onChange={event=>setCorrection(current=>({...current,homeScore:event.target.value}))}/></label></div>}<button disabled={scoringBusy||!correction.gameId||correction.awayScore===''||correction.homeScore===''} onClick={()=>action('correct_game',correction)}>Save Final Score & Regrade</button></section>}
    </div>
  </section></main>;
}
